modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL=""
license="MIT"

[[mods]]
modId="twilightforesttweaks"
version="${file.jarVersion}"
displayName="Twilight Forest Tweaks (TFT)"
authors="Meme Man"
description='''A small patch addon to Twilight Forest which adds compatibility with Curios API and introduces a number of niche features.'''
logoFile="tft_logo.png"

# Base
[[dependencies.twilightforesttweaks]]
	modId="forge"
	mandatory=true
	versionRange="[36.2.20,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.twilightforesttweaks]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.16.5,1.17]"
	ordering="NONE"
	side="BOTH"

# Libraries
[[dependencies.twilightforesttweaks]]
	modId="twilightforest"
	mandatory=true
	versionRange="[4.0.870,)"
	ordering="NONE"
	side="BOTH"

# Extras
	# COMMON
[[dependencies.twilightforesttweaks]]
	modId="curios"
	mandatory=false
	versionRange="[1.16.5-4.1.0.0,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.twilightforesttweaks]]
	modId="jei"
	mandatory=false
	versionRange="[7.7.1.152,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.twilightforesttweaks]]
	modId="jeresources"
	mandatory=false
	versionRange="[0.12,]"
	ordering="AFTER"
	side="BOTH"
	
[[dependencies.twilightforesttweaks]]
	modId="jeed"
	mandatory=false
	versionRange="[1.16.5-1.6,]"
	ordering="AFTER"
	side="BOTH"
	
[[dependencies.twilightforesttweaks]]
	modId="theoneprobe"
	mandatory=false
	versionRange="[1.16-3.1.7,]"
	ordering="AFTER"
	side="BOTH"

[[dependencies.twilightforesttweaks]]
	modId="datafixerslayer"
	mandatory=false
	versionRange="[1.0-3,]"
	ordering="AFTER"
	side="BOTH"
	
	# CLIENT
[[dependencies.twilightforesttweaks]]
	modId="appleskin"
	mandatory=false
	versionRange="[mc1.16.5-2.4.0,]"
	ordering="AFTER"
	side="CLIENT"

[[dependencies.twilightforesttweaks]]
	modId="configured"
	mandatory=false
	versionRange="[1.5.3,]"
	ordering="AFTER"
	side="CLIENT"

[[dependencies.twilightforesttweaks]]
	modId="catalogue"
	mandatory=false
	versionRange="[1.6.1,]"
	ordering="AFTER"
	side="CLIENT"

[[dependencies.twilightforesttweaks]]
	modId="gamemenumodoption"
	mandatory=false
	versionRange="[1.8.2,]"
	ordering="AFTER"
	side="CLIENT"